version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: labvet_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: labvet
      POSTGRES_USER: labvet_user
      POSTGRES_PASSWORD: labvet_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - labvet_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: labvet_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@labvet.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - labvet_network
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  labvet_network:
    driver: bridge
